version: '3.6'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile
       target: test

    volumes:
      - ./artifacts:/pyhrp/artifacts
      - ./test:/pyhrp/test
      - ./pyhrp:/pyhrp/pyhrp:ro
