version: '3.6'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile
       target: test

    volumes:
      - ./artifacts:/pyhrp/artifacts
      - ./test:/pyhrp/test:ro
      - ./pyhrp:/pyhrp/pyhrp:ro

  lint:
    build:
       context: .
       dockerfile: Dockerfile
       target: lint

    volumes:
      - ./pyhrp:/pyhrp/pyhrp:ro
      - ./.pylintrc:/pyhrp/.pylintrc:ro