[tool.poetry]
name = "pyhrp"
version = "0.0.0"
description = "..."
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/tschm/pyhrp"
packages = [{include = "pyhrp"}]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
pandas = ">=2.0.0"
scipy = ">=1.10.0"
matplotlib = ">=3.3.3"
scikit-learn = ">=0.24.1"

[tool.poetry.dev-dependencies]
pytest = "7.4.0"
pytest-cov = "*"
mock = "*"

[tool.poetry.group.dev.dependencies]
loguru = "*"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.masonry.api"
